document.addEventListener("DOMContentLoaded", () => {
    const container = document.getElementById('stock-container');
    const timestampEl = document.getElementById('timestamp');

    // Fetch the JSON generated by the Python script
    fetch('data/stocks.json')
        .then(response => {
            if (!response.ok) {
                throw new Error("Network response was not ok");
            }
            return response.json();
        })
        .then(data => {
            container.innerHTML = ''; // Clear loading state
            
            if (data.length > 0) {
                timestampEl.innerText = `Last Updated: ${data[0].last_updated}`;
            }

            data.forEach(stock => {
                // Determine styling based on positive or negative movement
                const isPositive = stock.change_percent >= 0;
                const changeClass = isPositive ? 'up' : 'down';
                const sign = isPositive ? '+' : '';

                // Create the card
                const card = document.createElement('div');
                card.className = 'stock-card';
                
                card.innerHTML = `
                    <div class="ticker">${stock.ticker}</div>
                    <div class="price">₹/bz ${stock.price}</div>
                    <div class="change ${changeClass}">${sign}${stock.change_percent}%</div>
                `;
                
                container.appendChild(card);
            });
        })
        .catch(error => {
            console.error('Error fetching stock data:', error);
            container.innerHTML = '<p><strong>Error loading data. Ensure the Python script has run and generated data/stocks.json.</strong></p>';
        });
});
